version: 2
jobs:
  build-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Test
          command: ./test.sh
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.14
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker buildx create --platform linux/amd64,linux/arm/v7 --use
          ./publish.sh

workflows:
  version: 2
  build-main:
    jobs:
      # - build-test
      - publish:
          context:
            - Docker Credentials
          # requires:
          #   - build-test
          filters:
            branches:
              only:
                - main
                - develop
                - feature/ci-cd-integration
