version: 2
jobs:
  build-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Test
          command: ./test.sh
  publish:
    docker:
      - image: drpsychick/dind-buildx:19-dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - run:
          name: Setup Docker buildx
          command: |
            docker buildx install
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create xbuilder
            docker buildx create xbuilder --name xbuilder --use
      - run:
          name: Publish Container
          command: ./publish.sh

workflows:
  version: 2
  build-main:
    jobs:
      - build-test
      - publish:
          context:
            - Docker Credentials
          requires:
            - build-test
          filters:
            branches:
              only:
                - main
                - develop
